# Generated by Django 5.2 on 2025-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file if not using a URL.', null=True, upload_to='videos/'),
        ),
    ]
