# Generated by Django 5.2 on 2025-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='screen_reader_hint',
            field=models.TextField(blank=True, help_text='Hint for screen reader users.'),
        ),
    ]
