# Generated by Django 5.2 on 2025-06-05 11:32

import core.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_screen_reader_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='braille_file',
            field=models.FileField(blank=True, null=True, upload_to='braille/', validators=[core.courses.models.validate_braille_file]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='captions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='screen_reader_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='screen_reader_hint',
            field=models.TextField(blank=True),
        ),
    ]
